defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: retro
  username: root
  password:

development:
  <<: *defaults
  database: retro_dev

test:
  <<: *defaults
  database: retro_test

production:
  <<: *defaults
  encoding: utf8
  database: <%=ENV['OPENSHIFT_APP_NAME']%>
  pool: 5
  host: <%=ENV['OPENSHIFT_MYSQL_DB_HOST']%>
  port: <%=ENV['OPENSHIFT_MYSQL_DB_PORT']%>
  username: <%=ENV['OPENSHIFT_MYSQL_DB_USERNAME']%>
  password: <%=ENV['OPENSHIFT_MYSQL_DB_PASSWORD']%>
  socket: <%=ENV['OPENSHIFT_MYSQL_DB_SOCKET']%>
