mysql:
  development:
    adapter: mysql2
    database: retro_development
    username: root
    encoding: utf8
    password:
    host: localhost

  production:
    adapter: mysql2
    database: retro_production
    username: retro
    encoding: utf8
    password: retro
    host: localhost

  test:
    adapter: mysql2
    database: retro_test
    username: retro
    encoding: utf8
    password: retro
    host: localhost
